version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  mongo:
    image: 'mongo:latest'
    volumes:
    - mongo_data:/data/db
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    ports:
      - 9200:9200
    volumes:
    - elasticsearch_data:/bitnami/elasticsearch/data

volumes:
  mongo_data:
  elasticsearch_data:
